import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { PlanningSheet } from '../../types';
import apiService from '../../services/api';
import './Planning.css';

const PlanningView: React.FC = () => {
  const { planningId } = useParams<{ planningId: string }>();
  const navigate = useNavigate();

  const [planning, setPlanning] = useState<PlanningSheet | null>(null);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  useEffect(() => {
    if (planningId) {
      loadPlanning();
    }
  }, [planningId]);

  const loadPlanning = async () => {
    if (!planningId) return;

    try {
      // We don't have a direct get-by-id endpoint, so we'll get it from the URL parameters
      // In a real app, you'd fetch it properly. For now, we'll handle this differently
      setError('Loading planning sheet...');
    } catch (err: any) {
      setError(err.response?.data?.error || 'Failed to load planning');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleRegenerate = async () => {
    if (!planningId || !window.confirm('Regenerate this planning sheet?')) return;

    try {
      await apiService.regeneratePlanning(planningId);
      setSuccess('Planning sheet regenerated!');
      await loadPlanning();
    } catch (err: any) {
      setError(err.response?.data?.error || 'Failed to regenerate');
    }
  };

  if (loading) return <div className="loading">Loading...</div>;
  if (!planning) {
    return (
      <div className="planning-view">
        <div className="planning-header">
          <button onClick={() => navigate(-1)} className="btn-back">← Back</button>
          <h1>Planning Sheet</h1>
        </div>
        <div className="error-message">
          Planning sheet not found. This view requires navigation from the course page.
        </div>
        <button onClick={() => navigate('/dashboard')} className="btn-primary">
          Go to Dashboard
        </button>
      </div>
    );
  }

  return (
    <div className="planning-view">
      <div className="planning-header no-print">
        <button onClick={() => navigate(-1)} className="btn-back">← Back</button>
        <div className="planning-actions">
          <button onClick={handlePrint} className="btn-secondary">Print</button>
          <button onClick={handleRegenerate} className="btn-secondary">Regenerate</button>
        </div>
      </div>

      {error && <div className="error-message no-print">{error}</div>}
      {success && <div className="success-message no-print">{success}</div>}

      <div className="planning-sheet">
        <div className="sheet-header">
          <h1>Peer Study Session Planning Sheet</h1>
          <div className="sheet-meta">
            <p><strong>Week:</strong> {planning.weekNumber}</p>
            <p><strong>AI Generated by:</strong> {planning.aiProvider}</p>
            {planning.sessionDate && (
              <p><strong>Session Date:</strong> {new Date(planning.sessionDate).toLocaleDateString()}</p>
            )}
          </div>
        </div>

        <section className="sheet-section">
          <h2>Weekly Abstract</h2>
          <p>{planning.weeklyAbstract}</p>
        </section>

        <section className="sheet-section">
          <h2>Learning Objectives</h2>
          <ul className="objectives-list">
            {planning.learningObjectives.map((obj, idx) => (
              <li key={idx}>{obj}</li>
            ))}
          </ul>
        </section>

        <section className="sheet-section">
          <h2>Practice Questions</h2>
          <div className="questions-list">
            {planning.questions.map((q, idx) => (
              <div key={idx} className="question-item">
                <div className="question-header">
                  <span className="question-number">Q{idx + 1}</span>
                  <span className={`difficulty-badge ${q.difficulty}`}>{q.difficulty}</span>
                  <span className="time-estimate">{q.estimatedTime} min</span>
                </div>
                <p className="question-text">{q.questionText}</p>
                {q.expectedAnswer && (
                  <div className="expected-answer">
                    <strong>Expected Answer:</strong>
                    <p>{q.expectedAnswer}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        <section className="sheet-section">
          <h2>Assessment Methods</h2>
          <div className="assessments-list">
            {planning.assessmentMethods.map((am, idx) => (
              <div key={idx} className="assessment-item">
                <div className="assessment-header">
                  <h3>{am.methodName}</h3>
                  <span className="duration">{am.duration} min</span>
                </div>
                <p>{am.description}</p>
              </div>
            ))}
          </div>
        </section>

        {planning.additionalNotes && (
          <section className="sheet-section">
            <h2>Additional Notes for Session Lead</h2>
            <p className="notes">{planning.additionalNotes}</p>
          </section>
        )}

        <footer className="sheet-footer">
          <p>Generated on {new Date(planning.createdAt).toLocaleDateString()}</p>
          {planning.isCustomized && <p className="customized-badge">✏️ Customized by session lead</p>}
        </footer>
      </div>
    </div>
  );
};

export default PlanningView;
